version: '3'

services:
  web:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
